
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// French translations
const frTranslations: Record<string, string> = {
  // Common
  'language.fr': 'FR',
  'language.en': 'EN',
  
  // Navigation
  'nav.home': 'Accueil',
  'nav.about': 'À propos',
  'nav.programs': 'Programmes',
  'nav.activities': 'Activités',
  'nav.news': 'Actualités',
  'nav.documents': 'Documents',
  'nav.media': 'Multimédia',
  'nav.contact': 'Contact',
  'nav.admin': 'Admin',
  
  // News
  'news.title': 'Actualités',
  'news.subtitle': 'Restez informé des dernières nouvelles et événements concernant le Sénateur LAMBONI Mindi et son travail au service du Togo.',
  'news.search': 'Rechercher des actualités...',
  'news.categories.all': 'Toutes les catégories',
  'news.readMore': 'Lire plus',
  'news.readFull': 'Lire l\'article complet',
  'news.previous': 'Article précédent',
  'news.next': 'Article suivant',
  'news.view': 'Voir l\'article',
  'news.noResults': 'Aucun résultat trouvé',
  'news.noResultsDescription': 'Aucune actualité ne correspond à votre recherche. Essayez avec d\'autres termes ou catégories.',
  'news.resetSearch': 'Réinitialiser la recherche',
  'news.stayInformed': 'Restez informé',
  'news.newsletterDescription': 'Abonnez-vous à notre newsletter pour recevoir les dernières actualités et événements directement dans votre boîte de réception.',
  'news.emailPlaceholder': 'Votre adresse e-mail',
  'news.subscribe': 'S\'abonner',
  'news.related': 'Articles similaires',
  'news.share': 'Partager',
  'news.author': 'Bureau du Sénateur',
  'news.noRelated': 'Aucune actualité similaire disponible pour le moment.',
  'news.categories.title': 'Catégories',
  
  // Programs
  'programs.title': 'Nos Programmes',
  'programs.subtitle': 'Découvrez les différents programmes et initiatives mis en place par le Sénateur LAMBONI Mindi.',
  'programs.details': 'Détails',
  'programs.all': 'Tous les programmes',
  'programs.intro.title': 'Une vision transformatrice',
  'programs.intro.description': 'Nos programmes sont conçus pour répondre aux défis actuels du Togo tout en préparant l\'avenir. Chaque initiative s\'inscrit dans une vision globale de développement durable, inclusif et équitable. Découvrez ci-dessous nos domaines d\'intervention prioritaires.',
  'programs.areas': 'Domaines d\'Intervention',
  'programs.areas.subtitle': 'Les secteurs prioritaires où nous concentrons nos efforts pour un impact maximal',
  'programs.education': 'Éducation',
  'programs.education.description': 'Améliorer l\'accès à une éducation de qualité pour tous les enfants togolais, du primaire à l\'université.',
  'programs.education.item1': 'Construction d\'écoles',
  'programs.education.item2': 'Bourses d\'études',
  'programs.education.item3': 'Formation des enseignants',
  'programs.health': 'Santé',
  'programs.health.description': 'Renforcer le système de santé et améliorer l\'accès aux soins médicaux, particulièrement dans les zones rurales.',
  'programs.health.item1': 'Centres de santé communautaires',
  'programs.health.item2': 'Campagnes de vaccination',
  'programs.health.item3': 'Formation du personnel médical',
  'programs.infrastructure': 'Infrastructure',
  'programs.infrastructure.description': 'Développer les infrastructures essentielles pour stimuler le développement économique et améliorer la qualité de vie.',
  'programs.infrastructure.item1': 'Réhabilitation routière',
  'programs.infrastructure.item2': 'Accès à l\'eau potable',
  'programs.infrastructure.item3': 'Électrification rurale',
  'programs.agriculture': 'Agriculture',
  'programs.agriculture.description': 'Moderniser le secteur agricole pour assurer la sécurité alimentaire et créer des opportunités économiques.',
  'programs.agriculture.item1': 'Soutien aux coopératives',
  'programs.agriculture.item2': 'Techniques agricoles modernes',
  'programs.agriculture.item3': 'Financement agricole',
  'programs.impact': 'Notre Impact',
  'programs.impact.subtitle': 'Les résultats tangibles de nos programmes sur la vie des communautés togolaises',
  'programs.impact.schools': 'Écoles Construites',
  'programs.impact.schools.description': 'Offrant un accès à l\'éducation à plus de 15 000 enfants',
  'programs.impact.health': 'Centres de Santé',
  'programs.impact.health.description': 'Fournissant des soins médicaux à plus de 100 000 personnes',
  'programs.impact.roads': 'Km de Routes',
  'programs.impact.roads.description': 'Reliant des communautés isolées aux marchés et services',
  'programs.impact.farmers': 'Agriculteurs Soutenus',
  'programs.impact.farmers.description': 'Améliorant leurs rendements et leurs revenus',
  'programs.overview': 'Vue d\'ensemble du programme',
  'programs.objectives': 'Objectifs',
  'programs.objective1': 'Améliorer les conditions de vie',
  'programs.objective2': 'Renforcer les capacités locales',
  'programs.objective3': 'Promouvoir le développement durable',
  'programs.beneficiaries': 'Bénéficiaires',
  'programs.beneficiary1': 'Communautés rurales',
  'programs.beneficiary2': 'Jeunes et femmes',
  'programs.beneficiary3': 'Personnes vulnérables',
  'programs.duration': 'Durée et phases',
  'programs.phase1': 'Phase 1: Évaluation (3 mois)',
  'programs.phase2': 'Phase 2: Mise en œuvre (18 mois)',
  'programs.phase3': 'Phase 3: Suivi et évaluation (3 mois)',
  'programs.locations': 'Zones d\'intervention',
  'programs.location1': 'Région Maritime',
  'programs.location2': 'Région des Plateaux',
  'programs.location3': 'Région Centrale',
  'programs.keyActivities': 'Activités clés',
  'programs.activity1.title': 'Formation et renforcement des capacités',
  'programs.activity1.description': 'Ateliers et séminaires pour former les bénéficiaires aux techniques et compétences nécessaires',
  'programs.activity2.title': 'Dotation en équipements et matériels',
  'programs.activity2.description': 'Fourniture des outils et ressources nécessaires à la mise en œuvre des activités du programme',
  'programs.activity3.title': 'Sensibilisation et mobilisation communautaire',
  'programs.activity3.description': 'Campagnes d\'information et de sensibilisation pour promouvoir l\'adhésion des communautés',
  'programs.howToParticipate': 'Comment participer ou soutenir ce programme ?',
  'programs.participateDescription': 'Si vous souhaitez participer à ce programme ou apporter votre soutien, plusieurs options s\'offrent à vous. Contactez-nous pour explorer les possibilités de partenariat, de bénévolat ou de contribution financière.',
  'programs.backToPrograms': 'Retour aux programmes',
  'programs.similarPrograms': 'Programmes similaires',
  'programs.noSimilar': 'Aucun programme similaire disponible pour le moment.',
  'programs.targetCommunities': 'Communautés ciblées',
  'programs.budget': 'Budget',
  'programs.partners': 'Partenaires',
  'programs.contactInfo': 'Pour plus d\'informations sur ce programme, veuillez contacter le responsable du programme:',
  'programs.coordinator': 'Jean Kokou',
  'programs.coordinatorTitle': 'Coordinateur de Programme',
  'programs.notFound': 'Programme non trouvé',
  'programs.notFoundDescription': 'Le programme que vous recherchez n\'existe pas ou a été supprimé.',
  
  // Activities
  'activities.title': 'Activités & Événements',
  'activities.subtitle': 'Suivez l\'agenda et les interventions du Sénateur LAMBONI Mindi au service du développement du Togo.',
  'activities.upcoming': 'Événements à venir',
  'activities.recent': 'Activités récentes',
  'activities.viewAll': 'Voir toutes les activités',
  'activities.details': 'Détails',
  'activities.eventDetails': 'Détails de l\'événement',
  'activities.join': 'Participer',
  'activities.location': 'Lieu',
  'activities.datetime': 'Date et heure',
  'activities.calendar': 'Agenda',
  
  // Documents
  'documents.title': 'Documents',
  'documents.subtitle': 'Consultez et téléchargez les documents officiels et publications du bureau du Sénateur LAMBONI Mindi.',
  'documents.download': 'Télécharger',
  'documents.search': 'Rechercher des documents...',
  'documents.center': 'Centre de Documentation',
  'documents.centerDesc': 'Trouvez les documents officiels, rapports, discours, et publications du bureau du Sénateur LAMBONI Mindi.',
  'documents.featured': 'Document en Vedette',
  'documents.categories': 'Catégories',
  'documents.noResults': 'Aucun document trouvé',
  'documents.noResultsDesc': 'Aucun document ne correspond à votre recherche. Essayez avec d\'autres termes.',
  'documents.resetSearch': 'Réinitialiser la recherche',
  'documents.downloadReport': 'Télécharger le rapport',
  
  // About
  'about.title': 'À Propos du Sénateur LAMBONI Mindi',
  'about.subtitle': 'Un engagement inébranlable au service du peuple togolais et du développement national.',
  'about.biography': 'Biographie',
  'about.values': 'Nos Valeurs',
  'about.valuesSubtitle': 'Les principes fondamentaux qui guident notre action politique et notre engagement envers le peuple togolais',
  'about.achievements': 'Réalisations Majeures',
  'about.achievementsSubtitle': 'Un aperçu des projets significatifs menés par le Sénateur LAMBONI Mindi depuis son élection',
  'about.projects': 'Projets en cours',
  
  // Ajout des traductions pour le contenu biographique
  'about.bio.paragraph1': 'Né le 15 mai 1975 à Lomé, le Sénateur LAMBONI Mindi a consacré sa vie au service public et à l\'amélioration des conditions de vie des citoyens togolais. Après avoir obtenu un doctorat en sciences politiques à l\'Université de Paris-Sorbonne, il a entamé une carrière dans l\'administration publique avant d\'être élu au Sénat en 2018.',
  'about.bio.paragraph2': 'Fort d\'une expérience de plus de 20 ans dans le domaine du développement communautaire, il a œuvré pour la mise en place de nombreux projets d\'infrastructure, d\'éducation et de santé dans différentes régions du Togo.',
  'about.bio.paragraph3': 'Sa vision d\'un Togo prospère et équitable guide chacune de ses actions et initiatives législatives. Il est particulièrement engagé dans les domaines de l\'éducation, de la santé et du développement rural.',
  
  // Valeurs
  'about.value.integrity.title': 'Intégrité',
  'about.value.integrity.description': 'Nous agissons avec honnêteté et transparence dans toutes nos actions, respectant nos engagements envers les citoyens.',
  'about.value.solidarity.title': 'Solidarité',
  'about.value.solidarity.description': 'Nous défendons l\'égalité des chances et l\'accès aux services essentiels pour tous les citoyens, où qu\'ils se trouvent.',
  'about.value.excellence.title': 'Excellence',
  'about.value.excellence.description': 'Nous visons l\'excellence dans tous nos projets, avec une attention particulière aux détails et à la qualité des résultats.',
  
  // Réalisations
  'about.achievements.2022.title': '2022-2023',
  'about.achievements.2022.item1': 'Mise en place d\'un programme de bourses pour 500 étudiants défavorisés',
  'about.achievements.2022.item2': 'Construction de trois centres de santé dans la région Maritime',
  'about.achievements.2022.item3': 'Inauguration d\'un centre de formation professionnelle à Kara',
  
  'about.achievements.2020.title': '2020-2021',
  'about.achievements.2020.item1': 'Développement d\'un programme d\'accès à l\'eau potable dans 25 villages',
  'about.achievements.2020.item2': 'Initiative de reboisement avec la plantation de 10 000 arbres',
  'about.achievements.2020.item3': 'Modernisation des équipements de 15 écoles primaires',
  
  'about.achievements.2018.title': '2018-2019',
  'about.achievements.2018.item1': 'Lancement d\'un programme de soutien aux coopératives agricoles',
  'about.achievements.2018.item2': 'Organisation de 30 séminaires de formation pour jeunes entrepreneurs',
  'about.achievements.2018.item3': 'Amélioration des infrastructures routières de quatre communes rurales',
  
  'about.achievements.ongoing.item1': 'Développement d\'un incubateur de start-ups technologiques',
  'about.achievements.ongoing.item2': 'Création d\'un réseau de bibliothèques communautaires',
  'about.achievements.ongoing.item3': 'Programme d\'énergies renouvelables pour les zones rurales',
  
  // Media
  'media.title': 'Galerie Multimédia',
  'media.subtitle': 'Découvrez les photos, vidéos et enregistrements audio des activités et événements du Sénateur LM.',
  'media.photos': 'Photos',
  'media.videos': 'Vidéos',
  'media.audio': 'Audio',
  'media.all': 'Tout',
  'media.search': 'Rechercher des médias...',
  'media.noResults': 'Aucun média trouvé',
  'media.noResultsDescription': 'Aucun contenu ne correspond au filtre sélectionné.',
  'media.viewAll': 'Voir tout le contenu',
  'media.view': 'Voir',
  'media.play': 'Lire',
  'media.download': 'Télécharger',
  'media.filter': 'Filtrer:',
  'media.featuredVideo': 'Vidéo à la Une',
  'media.featuredVideoSubtitle': 'Découvrez la dernière allocation du Sénateur LM concernant les projets de développement rural',
  'media.videoTitle': 'Discours: Plan de développement rural 2024-2030',
  'media.videoDescription': 'Dans cette allocution, le Sénateur LM présente les grandes lignes du plan de développement rural pour les six prochaines années, avec un focus particulier sur l\'accès à l\'eau potable et la modernisation des infrastructures agricoles.',
  'media.watchOnYoutube': 'Voir sur YouTube',
  'media.downloadableResources': 'Ressources Téléchargeables',
  'media.downloadableResourcesSubtitle': 'Photos officielles, logos et autres ressources médiatiques disponibles pour la presse et le public',
  'media.officialPhotos': 'Photos Officielles',
  'media.officialPhotosDesc': 'Photos haute résolution du Sénateur LM pour usage médiatique et publications.',
  'media.broll': 'Vidéos B-Roll',
  'media.brollDesc': 'Séquences vidéo libres de droits des activités récentes du Sénateur.',
  'media.logos': 'Logos et Graphiques',
  'media.logosDesc': 'Éléments visuels officiels aux formats vectoriels et bitmap.',
  'media.downloadPack': 'Télécharger le pack',
  
  // 404
  '404.title': '404',
  '404.subtitle': 'La page que vous recherchez n\'existe pas',
  '404.description': 'La page que vous essayez d\'accéder a peut-être été déplacée, supprimée, ou n\'a jamais existé.',
  '404.backToHome': 'Retour à l\'accueil',
  
  // Contact
  'contact.title': 'Contactez-nous',
  'contact.subtitle': 'Nous sommes à votre écoute. N\'hésitez pas à nous contacter pour toute question ou suggestion.',
  'contact.address': 'Adresse',
  'contact.phone': 'Téléphone',
  'contact.email': 'Email',
  'contact.hours': 'Horaires',
  'contact.formTitle': 'Envoyez-nous un message',
  'contact.fullName': 'Nom complet',
  'contact.yourName': 'Votre nom',
  'contact.yourEmail': 'votre.email@exemple.com',
  'contact.subject': 'Sujet',
  'contact.subjectPlaceholder': 'Sujet de votre message',
  'contact.message': 'Message',
  'contact.messagePlaceholder': 'Votre message...',
  'contact.send': 'Envoyer le message',
  'contact.faq': 'Questions fréquentes',
  'contact.faqSubtitle': 'Trouvez rapidement des réponses aux questions les plus courantes',
  'contact.stayInTouch': 'Restons en contact',
  'contact.newsletter': 'Inscrivez-vous à notre newsletter pour recevoir les dernières nouvelles et mises à jour',
  'contact.signUp': 'S\'inscrire',
  
  // Index
  'index.hero.title': 'Sénateur LAMBONI Mindi',
  'index.hero.subtitle': 'Au service du Togo et de ses citoyens',
  'index.hero.cta': 'Découvrez nos initiatives',
  'index.about.title': 'À Propos',
  'index.about.description': 'Sénateur engagé pour le développement du Togo, avec un focus sur l\'éducation, la santé et l\'agriculture.',
  'index.about.readMore': 'En savoir plus',
  'index.whatWeDo.title': 'Ce que nous faisons',
  'index.whatWeDo.description': 'Découvrez nos domaines d\'action et nos initiatives pour le développement du Togo.',
  'index.stats.title': 'Notre Impact',
  'index.stats.description': 'Quelques chiffres qui témoignent de notre engagement et de nos résultats.',
  'index.contact.title': 'Contactez-nous',
  'index.contact.description': 'Besoin d\'information ou envie de collaborer? N\'hésitez pas à nous contacter.',
  
  // Admin
  'admin.dashboard': 'Tableau de bord',
  'admin.login': 'Connexion administrateur',
  'admin.loginDesc': 'Connectez-vous pour accéder au panneau d\'administration.',
  'admin.username': 'Nom d\'utilisateur',
  'admin.password': 'Mot de passe',
  'admin.loginButton': 'Se connecter',
  'admin.loginError': 'Identifiant ou mot de passe incorrect',
  'admin.access': 'Accès administrateur requis',
  'admin.accessDesc': 'Vous devez vous connecter pour accéder au panneau d\'administration.',
  'admin.loginSuccess': 'Connexion réussie',
  'admin.loginSuccessDesc': 'Bienvenue dans le panneau d\'administration.',
  'admin.resetData': 'Données réinitialisées',
  'admin.resetDataDesc': 'Toutes les données du site ont été remises à leur état par défaut.',
  'admin.stats': 'Statistiques du site',
  'admin.statsDesc': 'Aperçu des performances du site',
  'admin.recentActivity': 'Activité récente',
  'admin.recentActivityDesc': 'Dernières actions sur le site',
  'admin.quickManagement': 'Gestion rapide',
  'admin.quickManagementDesc': 'Accédez rapidement aux fonctionnalités clés',
  'admin.systemActions': 'Actions système',
  'admin.systemActionsDesc': 'Gestion des données système',
  'admin.users': 'Utilisateurs',
  'admin.media': 'Médias',
  'admin.messages': 'Messages',
  'admin.settings': 'Paramètres',
  'admin.resetDataAction': 'Réinitialiser les données',
  'admin.exportContacts': 'Exporter les contacts',
  'admin.generateReport': 'Générer un rapport',
  
  // Footer
  'footer.quickLinks': 'Liens Rapides',
  'footer.resources': 'Ressources',
  'footer.newsletter': 'Newsletter',
  'footer.newsletterDesc': 'Abonnez-vous pour recevoir les dernières nouvelles et mises à jour.',
  'footer.rights': 'Tous droits réservés.',
  'footer.emailPlaceholder': 'Votre email',
};

// English translations
const enTranslations: Record<string, string> = {
  // Common
  'language.fr': 'FR',
  'language.en': 'EN',
  
  // Navigation
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.programs': 'Programs',
  'nav.activities': 'Activities',
  'nav.news': 'News',
  'nav.documents': 'Documents',
  'nav.media': 'Media',
  'nav.contact': 'Contact',
  'nav.admin': 'Admin',
  
  // News
  'news.title': 'News',
  'news.subtitle': 'Stay informed about the latest news and events concerning Senator LAMBONI Mindi and his work serving Togo.',
  'news.search': 'Search news...',
  'news.categories.all': 'All categories',
  'news.readMore': 'Read more',
  'news.readFull': 'Read full article',
  'news.previous': 'Previous article',
  'news.next': 'Next article',
  'news.view': 'View article',
  'news.noResults': 'No results found',
  'news.noResultsDescription': 'No news matches your search. Try with other terms or categories.',
  'news.resetSearch': 'Reset search',
  'news.stayInformed': 'Stay informed',
  'news.newsletterDescription': 'Subscribe to our newsletter to receive the latest news and events directly in your inbox.',
  'news.emailPlaceholder': 'Your email address',
  'news.subscribe': 'Subscribe',
  'news.related': 'Related Articles',
  'news.share': 'Share',
  'news.author': 'Senator\'s Office',
  'news.noRelated': 'No similar news available at the moment.',
  'news.categories.title': 'Categories',
  
  // Programs
  'programs.title': 'Our Programs',
  'programs.subtitle': 'Discover the various programs and initiatives implemented by Senator LAMBONI Mindi.',
  'programs.details': 'Details',
  'programs.all': 'All programs',
  'programs.intro.title': 'A transformative vision',
  'programs.intro.description': 'Our programs are designed to address Togo\'s current challenges while preparing for the future. Each initiative is part of a global vision of sustainable, inclusive and equitable development. Discover our priority areas of intervention below.',
  'programs.areas': 'Areas of Intervention',
  'programs.areas.subtitle': 'The priority sectors where we focus our efforts for maximum impact',
  'programs.education': 'Education',
  'programs.education.description': 'Improve access to quality education for all Togolese children, from primary to university.',
  'programs.education.item1': 'School construction',
  'programs.education.item2': 'Scholarships',
  'programs.education.item3': 'Teacher training',
  'programs.health': 'Health',
  'programs.health.description': 'Strengthen the health system and improve access to medical care, particularly in rural areas.',
  'programs.health.item1': 'Community health centers',
  'programs.health.item2': 'Vaccination campaigns',
  'programs.health.item3': 'Medical staff training',
  'programs.infrastructure': 'Infrastructure',
  'programs.infrastructure.description': 'Develop essential infrastructure to stimulate economic development and improve quality of life.',
  'programs.infrastructure.item1': 'Road rehabilitation',
  'programs.infrastructure.item2': 'Access to clean water',
  'programs.infrastructure.item3': 'Rural electrification',
  'programs.agriculture': 'Agriculture',
  'programs.agriculture.description': 'Modernize the agricultural sector to ensure food security and create economic opportunities.',
  'programs.agriculture.item1': 'Support for cooperatives',
  'programs.agriculture.item2': 'Modern agricultural techniques',
  'programs.agriculture.item3': 'Agricultural financing',
  'programs.impact': 'Our Impact',
  'programs.impact.subtitle': 'The tangible results of our programs on the lives of Togolese communities',
  'programs.impact.schools': 'Schools Built',
  'programs.impact.schools.description': 'Providing access to education for more than 15,000 children',
  'programs.impact.health': 'Health Centers',
  'programs.impact.health.description': 'Providing medical care to more than 100,000 people',
  'programs.impact.roads': 'Km of Roads',
  'programs.impact.roads.description': 'Connecting isolated communities to markets and services',
  'programs.impact.farmers': 'Farmers Supported',
  'programs.impact.farmers.description': 'Improving their yields and incomes',
  'programs.overview': 'Program Overview',
  'programs.objectives': 'Objectives',
  'programs.objective1': 'Improve living conditions',
  'programs.objective2': 'Strengthen local capacities',
  'programs.objective3': 'Promote sustainable development',
  'programs.beneficiaries': 'Beneficiaries',
  'programs.beneficiary1': 'Rural communities',
  'programs.beneficiary2': 'Youth and women',
  'programs.beneficiary3': 'Vulnerable people',
  'programs.duration': 'Duration and phases',
  'programs.phase1': 'Phase 1: Assessment (3 months)',
  'programs.phase2': 'Phase 2: Implementation (18 months)',
  'programs.phase3': 'Phase 3: Monitoring and evaluation (3 months)',
  'programs.locations': 'Intervention areas',
  'programs.location1': 'Maritime Region',
  'programs.location2': 'Plateaux Region',
  'programs.location3': 'Central Region',
  'programs.keyActivities': 'Key Activities',
  'programs.activity1.title': 'Training and capacity building',
  'programs.activity1.description': 'Workshops and seminars to train beneficiaries in necessary techniques and skills',
  'programs.activity2.title': 'Equipment and materials provision',
  'programs.activity2.description': 'Providing tools and resources needed for the implementation of program activities',
  'programs.activity3.title': 'Awareness and community mobilization',
  'programs.activity3.description': 'Information and awareness campaigns to promote community support',
  'programs.howToParticipate': 'How to participate or support this program?',
  'programs.participateDescription': 'If you wish to participate in this program or provide your support, several options are available. Contact us to explore partnership, volunteering, or financial contribution possibilities.',
  'programs.backToPrograms': 'Back to programs',
  'programs.similarPrograms': 'Similar Programs',
  'programs.noSimilar': 'No similar programs available at the moment.',
  'programs.targetCommunities': 'Target communities',
  'programs.budget': 'Budget',
  'programs.partners': 'Partners',
  'programs.contactInfo': 'For more information about this program, please contact the program manager:',
  'programs.coordinator': 'Jean Kokou',
  'programs.coordinatorTitle': 'Program Coordinator',
  'programs.notFound': 'Program not found',
  'programs.notFoundDescription': 'The program you are looking for does not exist or has been removed.',
  
  // Activities
  'activities.title': 'Activities & Events',
  'activities.subtitle': 'Follow Senator LAMBONI Mindi\'s agenda and interventions serving Togo\'s development.',
  'activities.upcoming': 'Upcoming events',
  'activities.recent': 'Recent activities',
  'activities.viewAll': 'View all activities',
  'activities.details': 'Details',
  'activities.eventDetails': 'Event details',
  'activities.join': 'Join',
  'activities.location': 'Location',
  'activities.datetime': 'Date and time',
  'activities.calendar': 'Calendar',
  
  // Documents
  'documents.title': 'Documents',
  'documents.subtitle': 'Access and download official documents and publications from Senator LAMBONI Mindi\'s office.',
  'documents.download': 'Download',
  'documents.search': 'Search documents...',
  'documents.center': 'Documentation Center',
  'documents.centerDesc': 'Find official documents, reports, speeches, and publications from Senator LAMBONI Mindi\'s office.',
  'documents.featured': 'Featured Document',
  'documents.categories': 'Categories',
  'documents.noResults': 'No documents found',
  'documents.noResultsDesc': 'No documents match your search. Try with other terms.',
  'documents.resetSearch': 'Reset search',
  'documents.downloadReport': 'Download report',
  
  // About
  'about.title': 'About Senator LAMBONI Mindi',
  'about.subtitle': 'An unwavering commitment to serve the Togolese people and national development.',
  'about.biography': 'Biography',
  'about.values': 'Our Values',
  'about.valuesSubtitle': 'The fundamental principles that guide our political actions and our commitment to the Togolese people',
  'about.achievements': 'Major Achievements',
  'about.achievementsSubtitle': 'An overview of significant projects led by Senator LAMBONI Mindi since his election',
  'about.projects': 'Ongoing projects',
  
  // Ajout des traductions anglaises pour le contenu biographique
  'about.bio.paragraph1': 'Born on May 15, 1975 in Lomé, Senator LAMBONI Mindi has dedicated his life to public service and improving the living conditions of Togolese citizens. After obtaining a doctorate in political science from the University of Paris-Sorbonne, he began a career in public administration before being elected to the Senate in 2018.',
  'about.bio.paragraph2': 'With more than 20 years of experience in community development, he has worked to implement numerous infrastructure, education, and health projects in different regions of Togo.',
  'about.bio.paragraph3': 'His vision of a prosperous and equitable Togo guides each of his actions and legislative initiatives. He is particularly committed to the fields of education, health, and rural development.',
  
  // Valeurs
  'about.value.integrity.title': 'Integrity',
  'about.value.integrity.description': 'We act with honesty and transparency in all our actions, respecting our commitments to citizens.',
  'about.value.solidarity.title': 'Solidarity',
  'about.value.solidarity.description': 'We defend equal opportunities and access to essential services for all citizens, wherever they may be.',
  'about.value.excellence.title': 'Excellence',
  'about.value.excellence.description': 'We aim for excellence in all our projects, with particular attention to detail and quality results.',
  
  // Achievements
  'about.achievements.2022.title': '2022-2023',
  'about.achievements.2022.item1': 'Implementation of a scholarship program for 500 disadvantaged students',
  'about.achievements.2022.item2': 'Construction of three health centers in the Maritime region',
  'about.achievements.2022.item3': 'Inauguration of a vocational training center in Kara',
  
  'about.achievements.2020.title': '2020-2021',
  'about.achievements.2020.item1': 'Development of a drinking water access program in 25 villages',
  'about.achievements.2020.item2': 'Reforestation initiative with the planting of 10,000 trees',
  'about.achievements.2020.item3': 'Modernization of equipment in 15 primary schools',
  
  'about.achievements.2018.title': '2018-2019',
  'about.achievements.2018.item1': 'Launch of a support program for agricultural cooperatives',
  'about.achievements.2018.item2': 'Organization of 30 training seminars for young entrepreneurs',
  'about.achievements.2018.item3': 'Improvement of road infrastructure in four rural communes',
  
  'about.achievements.ongoing.item1': 'Development of a technology startup incubator',
  'about.achievements.ongoing.item2': 'Creation of a network of community libraries',
  'about.achievements.ongoing.item3': 'Renewable energy program for rural areas',
  
  // Media
  'media.title': 'Media Gallery',
  'media.subtitle': 'Discover photos, videos and audio recordings of Senator LM\'s activities and events.',
  'media.photos': 'Photos',
  'media.videos': 'Videos',
  'media.audio': 'Audio',
  'media.all': 'All',
  'media.search': 'Search media...',
  'media.noResults': 'No media found',
  'media.noResultsDescription': 'No content matches the selected filter.',
  'media.viewAll': 'View all content',
  'media.view': 'View',
  'media.play': 'Play',
  'media.download': 'Download',
  'media.filter': 'Filter:',
  'media.featuredVideo': 'Featured Video',
  'media.featuredVideoSubtitle': 'Watch Senator LM\'s latest address about rural development projects',
  'media.videoTitle': 'Speech: Rural Development Plan 2024-2030',
  'media.videoDescription': 'In this address, Senator LM presents the main lines of the rural development plan for the next six years, with a particular focus on access to clean water and modernization of agricultural infrastructure.',
  'media.watchOnYoutube': 'Watch on YouTube',
  'media.downloadableResources': 'Downloadable Resources',
  'media.downloadableResourcesSubtitle': 'Official photos, logos and other media resources available for the press and the public',
  'media.officialPhotos': 'Official Photos',
  'media.officialPhotosDesc': 'High resolution photos of Senator LM for media use and publications.',
  'media.broll': 'B-Roll Videos',
  'media.brollDesc': 'Royalty-free video footage of the Senator\'s recent activities.',
  'media.logos': 'Logos and Graphics',
  'media.logosDesc': 'Official visual elements in vector and bitmap formats.',
  'media.downloadPack': 'Download pack',
  
  // 404
  '404.title': '404',
  '404.subtitle': 'The page you are looking for does not exist',
  '404.description': 'The page you are trying to access may have been moved, deleted, or never existed.',
  '404.backToHome': 'Back to home',
  
  // Contact
  'contact.title': 'Contact Us',
  'contact.subtitle': 'We are listening. Feel free to contact us for any questions or suggestions.',
  'contact.address': 'Address',
  'contact.phone': 'Phone',
  'contact.email': 'Email',
  'contact.hours': 'Hours',
  'contact.formTitle': 'Send us a message',
  'contact.fullName': 'Full name',
  'contact.yourName': 'Your name',
  'contact.yourEmail': 'your.email@example.com',
  'contact.subject': 'Subject',
  'contact.subjectPlaceholder': 'Subject of your message',
  'contact.message': 'Message',
  'contact.messagePlaceholder': 'Your message...',
  'contact.send': 'Send message',
  'contact.faq': 'Frequently asked questions',
  'contact.faqSubtitle': 'Quickly find answers to the most common questions',
  'contact.stayInTouch': 'Stay in touch',
  'contact.newsletter': 'Sign up for our newsletter to receive the latest news and updates',
  'contact.signUp': 'Sign up',
  
  // Index
  'index.hero.title': 'Senator LAMBONI Mindi',
  'index.hero.subtitle': 'Serving Togo and its citizens',
  'index.hero.cta': 'Discover our initiatives',
  'index.about.title': 'About',
  'index.about.description': 'Senator committed to the development of Togo, with a focus on education, health and agriculture.',
  'index.about.readMore': 'Read more',
  'index.whatWeDo.title': 'What we do',
  'index.whatWeDo.description': 'Discover our areas of action and our initiatives for the development of Togo.',
  'index.stats.title': 'Our Impact',
  'index.stats.description': 'Some figures that testify to our commitment and our results.',
  'index.contact.title': 'Contact us',
  'index.contact.description': 'Need information or want to collaborate? Don\'t hesitate to contact us.',
  
  // Admin
  'admin.dashboard': 'Dashboard',
  'admin.login': 'Admin login',
  'admin.loginDesc': 'Log in to access the admin panel.',
  'admin.username': 'Username',
  'admin.password': 'Password',
  'admin.loginButton': 'Log in',
  'admin.loginError': 'Invalid username or password',
  'admin.access': 'Admin access required',
  'admin.accessDesc': 'You need to log in to access the admin panel.',
  'admin.loginSuccess': 'Login successful',
  'admin.loginSuccessDesc': 'Welcome to the admin panel.',
  'admin.resetData': 'Data reset',
  'admin.resetDataDesc': 'All site data has been reset to its default state.',
  'admin.stats': 'Site statistics',
  'admin.statsDesc': 'Overview of site performance',
  'admin.recentActivity': 'Recent activity',
  'admin.recentActivityDesc': 'Latest actions on the site',
  'admin.quickManagement': 'Quick management',
  'admin.quickManagementDesc': 'Quickly access key features',
  'admin.systemActions': 'System actions',
  'admin.systemActionsDesc': 'System data management',
  'admin.users': 'Users',
  'admin.media': 'Media',
  'admin.messages': 'Messages',
  'admin.settings': 'Settings',
  'admin.resetDataAction': 'Reset data',
  'admin.exportContacts': 'Export contacts',
  'admin.generateReport': 'Generate report',
  
  // Footer
  'footer.quickLinks': 'Quick Links',
  'footer.resources': 'Resources',
  'footer.newsletter': 'Newsletter',
  'footer.newsletterDesc': 'Subscribe to receive the latest news and updates.',
  'footer.rights': 'All rights reserved.',
  'footer.emailPlaceholder': 'Your email',
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Get initial language from localStorage or default to 'fr'
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage === 'en' || savedLanguage === 'fr') ? savedLanguage : 'fr';
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    const translations = language === 'fr' ? frTranslations : enTranslations;
    return translations[key] || key; // Return the key itself if no translation found
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
};

export default LanguageProvider;
