// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyqrrgzvowhjeoblevez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cXJyZ3p2b3doamVvYmxldmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTAxNjgsImV4cCI6MjA1Njg4NjE2OH0.0qcaeUIEW4gacesBNM_8eiB6R9IBMdG8vI8wG8Lh7mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});